### ISSUE TITLE
USER STORY: Adding Multiple Products

### ISSUE THREAD

**Issue by SooryaGeorge7** [SooryaGeorge7/Dental_Decor#10]
As a *** unauthenticated user/customer*** i can *** select multiple products and add them to my shopping basket *** so that ***add all desired products to the cart at once to save time***

** Acceptance Criteria **

- [x] On the products pages I can add more than one item to a shopping bag
- [x] When visiting the website I can navigate to the shopping bag and see what items are added

** Tasks **

- [x] Add feature or link for add-to-cart functionality
- [x]  Add feature to see what's in cart
