### ISSUE TITLE
USER STORY: Product quantity feature

### ISSUE THREAD

**Issue by SooryaGeorge7** [SooryaGeorge7/Dental_Decor#11]
As a ***unauthenticated user/customer** i can ***increase or decrease the quantity of products in my shopping basket *** so that ***so I have the freedom to change my mind if i want to***

** Acceptance Criteria **

- [x] On my shopping bag page, a  button to increase or decrease quantity can be seen.
- [x] When navigating the website shopping bag tab is always available.

** Tasks **

- [x] Make shopping cart link always visible
- [x] All Buttons/links to have increase/decrease functionality
