### ISSUE TITLE
Site Owner : Add new products in shop

### ISSUE THREAD

**Issue by SooryaGeorge7** [SooryaGeorge7/Dental_Decor#12]
As a ***site developer*** i can ***add new products to the shop*** so that ***there are more products in the store***

** Acceptance Criteria **

- [x] The newly added products should be seamlessly integrated into the shop, visible to customers, and searchable if applicable.

** Tasks **

- [x]  Create a product management link for the admin user or superuser
- [x]  Create a form with required fields to handle adding a product
