### ISSUE TITLE
Site Owner:Delete Products

### ISSUE THREAD

**Issue by SooryaGeorge7** [SooryaGeorge7/Dental_Decor#13]
As a ***site owner*** i can ***delete existing products from the shop*** so that *** users are not shown items that are no longer available***

** Acceptance Criteria **

- [x] The site owner should have a delete button
- [x] The deletion process should provide a confirmation to ensure the site owner's intention to delete the selected product.

** Tasks **

- [ ]Delete functionality should be implemented
- [ ]Create a confirmation prompt to delete product
