### ISSUE TITLE
Site Owner: Edit products

### ISSUE THREAD

**Issue by SooryaGeorge7** [SooryaGeorge7/Dental_Decor#14]
As a ***Site dev*** i can ***edit product information*** so that ***the website and product information is updated and relevant***

** Acceptance Criteria **

- [x] The site owner should be able to select a specific product to update its information
- [x] After successfully updating a product, the shop's user interface should reflect the changes, displaying the updated information and images for the product

** Tasks **

- [x] Create an edit button visible only to the admin user
 - [x] Make the editing process easy and intuitive
