### ISSUE TITLE
USER STORY: Direct to Checkout

### ISSUE THREAD

**Issue by SooryaGeorge7** [SooryaGeorge7/Dental_Decor#15]
As a ***unregistered user*** i can ***checkout *** so that ***i can purchase items without signing up***

** Acceptance Criteria **

- [x] When on checkout page checkout process is intuitive and easy to follow
- [x] When navigating a website checkout link is available without creating an account

** Tasks **

- [x] Create app for checkout
- [x] integrate Stripe API for secure payment
