### ISSUE TITLE
USER STORY: Card details

### ISSUE THREAD

**Issue by SooryaGeorge7** [SooryaGeorge7/Dental_Decor#18]
As a ***user*** i can ***put in my card details*** so that ***i can buy items with credit/debit cards***

***Acceptance Criteria***

- [x] When on checkout page I can put in my credit card details and make a purchase
- [x] checkout  payment process is easy and works accordingly

Acceptance criteria 3

***Tasks***

 - [x] Create card element
 - [x] Enable payment functionality
