### ISSUE TITLE
USER STORY: Checkout Form

### ISSUE THREAD

**Issue by SooryaGeorge7** [SooryaGeorge7/Dental_Decor#19]
As a ***authenticated user/customer*** i can ***add my details  to a secure checkout form*** so that ***i can see all the purchases i have made***

***Acceptance Criteria***
- [x] On checkout page checkout form is clearly displayed .
- [x] When scrolling through a checkout form a save to my profile check is avaliable.

***Tasks***
 - [x] Create a checkout form
