### ISSUE TITLE
USER STORY: Home page

### ISSUE THREAD

**Issue by SooryaGeorge7** [SooryaGeorge7/Dental_Decor#2]
As an ***unregistered user*** i would like to be able to  ***view the website homepage*** so that ***i can have an overview of the site.***

** Acceptance Criteria **

- [x] Home page must be responsive to different screen sizes.
- [x] Must have a clear layout with nav and footer.
- [x] User should be able to understand what the website is about easily.

** Tasks **

- [x] Create homepage wireframe and implement it accordingly
- [x] Create home app.
- [x] Create template for home page, linking to base.html
- [x] Add all features for homepage
