### ISSUE TITLE
USER STORY: Contact Us

### ISSUE THREAD

**Issue by SooryaGeorge7** [SooryaGeorge7/Dental_Decor#27]
As a ***User*** i can ***Send a Contact us Query*** so that ***i can have the necessary information i require regarding the products or the website information**

***Acceptance Criteria ***

- [x] Users can send a query via the contact us form.
- [x] Users can receive feedback on query

***Tasks***
- [x] Add contact us app
- [x] Add urls, models, templates
