### ISSUE TITLE
USER STORY: Navigation

### ISSUE THREAD

**Issue by SooryaGeorge7** [SooryaGeorge7/Dental_Decor#3]
As a ***unregistered customer*** i want to ***navigate website easily*** so that ***i can find what i am looking for without difficulty***

** Acceptance Criteria **

- [x] Links to navigation tabs must take user to desired location
- [x] Must have hover effect and be easily spotted
- [x] Can be easily accessible in any device size

** Tasks **

- [x] Add links to navbar.
- [x] Make navbar responsive.
