### ISSUE TITLE
USER STORY: Authentication and Authorization

### ISSUE THREAD

**Issue by SooryaGeorge7** [SooryaGeorge7/Dental_Decor#4]
As a ***User*** i can ***register for website*** so that ***i can login so that my data is already saved from registering***

** Acceptance Criteria **

- [x] User must be able email confirmation when registering for site.
- [x] User can successfully login after registering for site
- [x] User can successfully logout .

** Tasks **

- [x] Install allauth
- [x] Update settings.py
- [x] Add allauth templates

**Comment by VidyaYadavv1519** [comment]
Hi, is this issue still availabel ??
Can you assign me ??
