### ISSUE TITLE
USER STORY: Footer

### ISSUE THREAD

**Issue by SooryaGeorge7** [SooryaGeorge7/Dental_Decor#5]
As a ***User*** i can ***access the footer of the website*** so that ***i can visit the site's social media pages***

** Acceptance Criteria **

- [x] Footer must redirect user to relevant social media pages
- [x] Must be responsive to all device sizes

** Tasks **

- [x] Create base.html with header with nav and body with footer.
- [x] Add links to footer for social media pages.
- [x] Add copyright statement.
