### ISSUE TITLE
USER STORY: Products to shop

### ISSUE THREAD

**Issue by SooryaGeorge7** [SooryaGeorge7/Dental_Decor#6]
As an unregistered ***customer*** i can ***see all the products available on the website*** so that ***i can decide if the website has a product i want to purchase***

** Acceptance Criteria **

- [x] Products must be be seen by customer and the customer must be able to have an understanding of what each product is

** Tasks **

- [x] Add links to navbar.
- [x] Add links to product details page.
