### ISSUE TITLE
USER STORY: Product Details

### ISSUE THREAD

**Issue by SooryaGeorge7** [SooryaGeorge7/Dental_Decor#7]
As an ***unregistered customer *** i can ***see details of each product in shop*** so that *** i can make more of an informed decision to see whether i want to purchase a particular product***

** Acceptance Criteria **

- [x] Customer can see details for each product.
- [x] Customer can easily click a button for each product to see details for each product.

** Tasks **

- [x] Add links to navbar.
- [x] Make navbar responsive.
