### ISSUE TITLE
USER STORY: Sorting and filtering Products

### ISSUE THREAD

**Issue by SooryaGeorge7** [SooryaGeorge7/Dental_Decor#8]
As a ***customer*** i can ***sort or filter products*** so that ***i only see the products i want to see***

** Acceptance Criteria **

- [x] Customer can successfully sort according to price , name and all
- [x] Customer can successfully filter products according to wall art, sculpture, custom art and furniture.

** Tasks **

- [x] Add sorting section
- [x] Add filtering section
- [x] Add links each section
