### ISSUE TITLE
USER STORY: Select & Add Products

### ISSUE THREAD

**Issue by SooryaGeorge7** [SooryaGeorge7/Dental_Decor#9]
As a ***unauthenticated user/customer*** i can have ***functionality to select the product and add it to my shopping baske*** so that *** i can make more of an informed decision to see whether i want to purchase a particular product***

** Acceptance Criteria **

- [x] When on the shop's website adding to cart functionality is intuitive and clearly displayed
- [x] When on the shop's website shopping cart functionality is intuitive and visible to all users

** Tasks **

- [x] Create a view and template for a shopping bag
- [x] Add buttons or links to templates along with its functionality
